from .i_generate_pdf_repository import IPDFGeneratorRepository
from .i_image_extractor_repository import IImageExtractorRepository
from .i_ocr_repository import IOCRRepository
from .i_translate_section_repository import ITranslateSectionRepository
